import {
  Loader2,
  Moon,
  SunMedium,
  X,
  Search,
  LogOut,
  Pencil,
  Settings,
  Clock,
  CheckCircle2,
  FileEdit,
  PlusSquare,
  Trash,
  ListTodo,
  User,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  sun: SunMedium,
  moon: Moon,
  close: X,
  search: Search,
  logOut: LogOut,
  pencil: Pencil,
  settings: Settings,
  clock: Clock,
  checkCircle2: CheckCircle2,
  fileEdit: FileEdit,
  plusSquare: PlusSquare,
  trash: Trash,
  listTodo: ListTodo,
  user: User,
};
